GCOV_PROFILE := y
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/smmu
obj-$(CONFIG_MSMB_CAMERA_2016) += msm_isp.o msm_buf_mgr.o msm_isp_util.o msm_isp_axi_util.o msm_isp_stats_util.o
obj-$(CONFIG_MSMB_CAMERA_2016) += msm_isp47.o msm_isp46.o msm_isp44.o msm_isp40.o msm_isp32.o
